### ISSUE TITLE
i5 10500 iGPU only?

### ISSUE THREAD

**Issue by ahaadkabir** [goomadao/MSI-H410M-A-PRO-OpenCore-EFI#3]
Hi, can I use only UHD 630 graphics only for a single monitor via HDMI? No dedicated graphics. Thanks.

**Comment by goomadao** [comment]
You can use `07009B3E` instead of `0300C89B` in `DeviceProperties-Add-PciRoot(0x0)/Pci(0x2,0x0)-AAPL,ig-platform-id` (according to [Dortania's OpenCore Install Guide](https://dortania.github.io/OpenCore-Install-Guide/config.plist/comet-lake.html#deviceproperties)). But I'm not sure whether it works.

**Comment by ahaadkabir** [comment]
I have not still purchased the motherboard till now. if you could try checking weather it works or not than it would help me very much.

**Comment by goomadao** [comment]
I have no HDMI cable at this time. Sorry for that.
